ingressClassName: portal-ingress
ingressDomain: <replaced-ingress-nginx-ip>.nip.io
image: kubebb/component-store:latest
imagePullPolicy: IfNotPresent
resources:
  limits:
    cpu: "1"
    memory: 1024Mi
  requests:
    cpu: "100m"
    memory: 128Mi
