{{- if .Values.global.host -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.istio.io/inject: "false"
  labels:
    {{- include "tmf.portal.labels" . | nindent 4 }}
    system/svcName: {{ include "tmf.portal.fullname" . }}
  name: {{ include "tmf.portal.fullname" . }}
  namespace: {{ include "tmf.portal.namespace" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "tmf.portal.fullname" . }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        {{- include "tmf.portal.labels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /msa-manage
              port: 8989
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: {{ include "tmf.portal.fullname" . }}
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8989
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: {{ include "tmf.portal.serviceAccountName" . }}
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}