{{- if .Values.global.host -}}
{{- if .Values.psp.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tmf.portal.fullname" . }}-psp-role
  namespace: {{ include "tmf.portal.namespace" . }}
  labels:
    {{- include "tmf.portal.labels" . | nindent 4 }}
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include "tmf.portal.fullname" . }}
  verbs:
  - use
{{- end }}
{{- end }}