{{- if .Values.global.host -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "apm.api.fullname" . }}
rules:
  - apiGroups:
      - cluster.karmada.io
    resources:
      - '*'
    verbs:
      - get
      - list
  - apiGroups:
      - t7d.io
    resources:
      - tenantviews
      - namespaceviews
      - userviews
    verbs:
      - get
      - list
  - apiGroups:
      - mesh.t7d.io
    resources:
      - istios
      - meshes
    verbs:
      - get
      - list
  - apiGroups:
      - common.tenxcloud.com
    resources:
      - licenses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - common.tenxcloud.com
    resources:
      - licenseusings
    verbs:
      - get
      - list
      - create
  - apiGroups:
      - common.tenxcloud.com
    resources:
      - licenseusings/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
  - apiGroups:
      - iam.tenxcloud.com
    resources:
      - users
    verbs:
      - get
      - list
{{- end -}}