{{- if .Values.global.host -}}
{{- if .Values.psp.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "apm.api.fullname" . }}-psp-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apm.api.labels" . | nindent 4 }}
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include "apm.api.fullname" . }}
  verbs:
  - use
{{- end }}
{{- end }}