{{- if .Values.psp.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podsecuritypolicy
  namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podsecuritypolicy
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.global.namespace }}
{{- end }}