apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubebb-resource-reader
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - "core.kubebb.k8s.com.cn"
  resources:
  - ratings
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubebb-resource-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubebb-resource-reader
subjects:
- kind: Group
  name: resource-reader
