{{- if .Values.oidcServer.enabled -}}
apiVersion: core.kubebb.k8s.com.cn/v1alpha1
kind: Portal
metadata:
  name: oidc
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  entry: /oidc-public/index.html
  path: /oidc
{{- end }}