{{- if and (.Values.deployment.rating_enable) (.Capabilities.APIVersions.Has "tekton.dev/v1beta1" ) }}
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: {{ .Release.Name }}-reliability-helm-lint
  namespace: {{ .Release.Namespace }}
spec:
  params:
  - name: url
    type: string
  - name: component
    type: string
  - name: version
    type: string
  results:
  - name: LINT
    type: string
  steps:
    - name: helm-lint
      image: alpine/k8s:1.27.4
      script: |
        #!/usr/bin/env sh
        # Download and untar chart package
        helm pull --untar $(params.url)

        helm lint ./$(params.component)
        echo $? | tee $(results.LINT.path)
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name:  {{ .Release.Name }}-reliability
  annotations:
    tekton.dev/tags: {{ .Release.Name }}-reliability
    tekton.dev/displayName: "{{ .Release.Name }}"
    tekton.dev/platforms: "linux/amd64"
  namespace: {{ .Release.Namespace }}
spec:
  description: >-
    kubebb-core default pipeline
  params:
    - name: COMPONENT_NAME
      description: >-
        component name
    - name: REPOSITORY_NAME
      description: repository name
      default: "kubebb"
    - name: VERSION
      description: component version
    - name: URL
      description: the full URL of the component tgz file.
  results:
  - name: HELM_LINT
    value: $(tasks.{{ .Release.Name }}-helm-lint.results.LINT)
  tasks:
    - name: {{ .Release.Name }}-helm-lint
      retries: 2
      taskRef:
        resolver: cluster
        params:
        - name: kind
          value: task
        - name: name
          value: {{ .Release.Name }}-reliability-helm-lint
        - name: namespace
          value: {{ .Release.Namespace }}
      params:
        - name: url
          value: $(params.URL)
        - name: component
          value: $(params.COMPONENT_NAME)
        - name: version
          value: $(params.VERSION)
{{- end }}
