{{- if and (.Values.deployment.rating_enable) (.Capabilities.APIVersions.Has "tekton.dev/v1beta1" ) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "rating-name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "rating-name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "rating-name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
