{{- if and (.Values.deployment.rating_enable) (.Capabilities.APIVersions.Has "tekton.dev/v1beta1" ) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rating-name" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
