{{- if .Values.webhook.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webhook-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: {{ .Release.Name }}-kubebb-core
{{- end }}
