{{- if .Values.webhook.enable }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Release.Name }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Release.Name }}-webhook-svc
      namespace: {{ .Release.Namespace }}
      path: /mutate-core-kubebb-k8s-com-cn-v1alpha1-component
  failurePolicy: Fail
  name: component.kb.io
  rules:
  - apiGroups:
    - core.kubebb.k8s.com.cn
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - components
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Release.Name }}-webhook-svc
      namespace: {{ .Release.Namespace }}
      path: /mutate-core-kubebb-k8s-com-cn-v1alpha1-componentplan
  failurePolicy: Fail
  name: mcomponentplan.kb.io
  rules:
  - apiGroups:
    - core.kubebb.k8s.com.cn
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - componentplans
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Release.Name }}-webhook-svc
      namespace: {{ .Release.Namespace }}
      path: /mutate-core-kubebb-k8s-com-cn-v1alpha1-portal
  failurePolicy: Fail
  name: mportal.kb.io
  rules:
  - apiGroups:
    - core.kubebb.k8s.com.cn
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - portals
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Release.Name }}-webhook-svc
      namespace: {{ .Release.Namespace }}
      path: /mutate-core-kubebb-k8s-com-cn-v1alpha1-subscription
  failurePolicy: Fail
  name: msubscription.kb.io
  rules:
  - apiGroups:
    - core.kubebb.k8s.com.cn
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - subscriptions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Release.Name }}-webhook-svc
      namespace: {{ .Release.Namespace }}
      path: /mutate-core-kubebb-k8s-com-cn-v1alpha1-repository
  failurePolicy: Fail
  name: mrepository.kb.io
  rules:
  - apiGroups:
    - core.kubebb.k8s.com.cn
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - repositories
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Release.Name }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Release.Name }}-webhook-svc
      namespace: {{ .Release.Namespace }}
      path: /validate-core-kubebb-k8s-com-cn-v1alpha1-componentplan
  failurePolicy: Fail
  name: vcomponentplan.kb.io
  rules:
  - apiGroups:
    - core.kubebb.k8s.com.cn
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - componentplans
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Release.Name }}-webhook-svc
      namespace: {{ .Release.Namespace }}
      path: /validate-core-kubebb-k8s-com-cn-v1alpha1-portal
  failurePolicy: Fail
  name: vportal.kb.io
  rules:
  - apiGroups:
    - core.kubebb.k8s.com.cn
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - portals
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Release.Name }}-webhook-svc
      namespace: {{ .Release.Namespace }}
      path: /validate-core-kubebb-k8s-com-cn-v1alpha1-subscription
  failurePolicy: Fail
  name: vsubscription.kb.io
  rules:
  - apiGroups:
    - core.kubebb.k8s.com.cn
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - subscriptions
  sideEffects: None
{{- end }}
