{{- if and (.Values.deployment.rating_enable) (.Capabilities.APIVersions.Has "tekton.dev/v1beta1" ) }}
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rating-reliability-linting
  annotations:
    rating.core.kubebb.k8s.com.cn/type: reliability
    rating.core.kubebb.k8s.com.cn/weight: "1"
  namespace: {{ .Release.Namespace }}
spec:
  params:
  - name: url
    type: string
  - name: component
    type: string
  - name: version
    type: string
  results:
  - name: LINT
    type: string
  steps:
    - name: helm-lint
      image: kubebb/rating:v0.1.3
      script: |
        #!/usr/bin/env sh
        # Download and untar chart package
        helm pull --untar $(params.url)

        helm lint ./$(params.component)
        echo $? | tee $(results.LINT.path)
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name:  rating-reliability-pipeline
  annotations:
    tekton.dev/tags: {{ .Release.Name }}-reliability
    tekton.dev/displayName: "{{ .Release.Name }}"
    tekton.dev/platforms: "linux/amd64"
    core.kubebb.k8s.com.cn/dimension: reliability
  namespace: {{ .Release.Namespace }}
spec:
  description: >-
    kubebb-core default pipeline
  params:
    - name: COMPONENT_NAME
      description: >-
        component name
      type: string
    - name: REPOSITORY_NAME
      description: repository name
      default: "kubebb"
      type: string
    - name: VERSION
      description: component version
      type: string
    - name: URL
      description: the full URL of the component tgz file.
      type: string
  results:
  - name: HELM_LINT
    value: $(tasks.rating-reliability-linting.results.LINT)
  tasks:
    - name: rating-reliability-linting
      retries: 2
      taskRef:
        resolver: cluster
        params:
        - name: kind
          value: task
        - name: name
          value: rating-reliability-linting
        - name: namespace
          value: {{ .Release.Namespace }}
      params:
        - name: url
          value: $(params.URL)
        - name: component
          value: $(params.COMPONENT_NAME)
        - name: version
          value: $(params.VERSION)
{{- end }}
