apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "apm.operator.fullname" . }}
  labels:
    {{- include "apm.operator.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "apm.operator.fullname" . }}
    namespace: {{ include "apm.operator.namespace" . }}