apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "apm.operator.namespace" . }}/{{ include "apm.operator.fullname" . }}-ca
  name: {{ include "apm.operator.fullname" . }}
  labels:
    {{- include "apm.operator.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "apm.operator.fullname" . }}
        namespace: {{ include "apm.operator.namespace" . }}
        path: /apm/agent/install
        port: 443
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: {{ include "apm.operator.fullname" . }}.install.tenxcloud.com
    namespaceSelector: {}
    objectSelector:
      matchLabels:
        apm-injection: "true"
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: '*'
    sideEffects: None
    timeoutSeconds: 10
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "apm.operator.fullname" . }}
        namespace: {{ include "apm.operator.namespace" . }}
        path: /arthas/install
        port: 443
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: {{ include "apm.operator.fullname" . }}.arthas.tenxcloud.com
    namespaceSelector: {}
    objectSelector:
      matchLabels:
        arthas-injection: "true"
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: '*'
    sideEffects: None
    timeoutSeconds: 10