{{- if .Values.psp.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "apm.operator.fullname" . }}-psp-rolebinding
  namespace: {{ include "apm.operator.namespace" . }}
  labels:
    {{- include "apm.operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "apm.operator.fullname" . }}-psp-role
subjects:
- kind: ServiceAccount
  name: {{ include "apm.operator.fullname" . }}
  namespace: {{ include "apm.operator.namespace" . }}
{{- end }}
