apiVersion: v1
kind: Secret
metadata:
  name: pkcs12-password-secret
  namespace: {{ include "apm.operator.namespace" . }}
  labels:
    {{- include "apm.operator.labels" . | nindent 4 }}
data:
  password: dGVueGNsb3Vk
type: Opaque