apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "apm.operator.labels" . | nindent 4 }}
    system/svcName: {{ include "apm.operator.fullname" . }}
  name: {{ include "apm.operator.fullname" . }}
  namespace: {{ include "apm.operator.namespace" . }}
spec:
  ports:
    - name: tcp-apm-operator-0
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    k8s-app: {{ include "apm.operator.fullname" . }}
  type: {{ .Values.service.type }}