apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "apm.operator.fullname" . }}
  namespace: {{ include "apm.operator.namespace" . }}
  labels:
    {{- include "apm.operator.labels" . | nindent 4 }}