{{- if .Values.global.host -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "apm.portal.serviceAccountName" . }}
  namespace: {{ include "apm.portal.namespace" . }}
  labels:
    {{- include "apm.portal.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}