---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tmf.framework.fullname" . }}
  labels:
    {{- include "tmf.framework.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "tmf.framework.fullname" . }}
    namespace: {{ include "tmf.framework.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:serviceaccounts:event-rb
  labels:
    {{- include "tmf.framework.labels" . | nindent 4 }}
subjects:
  - kind: Group
    name: system:serviceaccounts
roleRef:
  kind: ClusterRole
  name: event-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tmf-env-injector-rule
subjects:
  - kind: ServiceAccount
    name: tmf-env-injector
    namespace: {{ include "tmf.framework.namespace" . }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io