---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "tmf.framework.namespace" . }}/{{ include "tmf.framework.fullname" . }}-ca
  name: {{ include "tmf.framework.fullname" . }}
  labels:
    {{- include "tmf.framework.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "tmf.framework.fullname" . }}
        namespace: {{ include "tmf.framework.namespace" . }}
        path: /service/enhance
        port: 443
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: {{ include "tmf.framework.fullname" . }}.enhance.tenxcloud.com
    namespaceSelector:
      matchLabels:
        tmf-env-injector: "true"
    objectSelector: {}
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: '*'
    sideEffects: None
    timeoutSeconds: 10
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "tmf.framework.fullname" . }}
        namespace: {{ include "tmf.framework.namespace" . }}
        path: /flow/agent/install
        port: 443
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: {{ include "tmf.framework.fullname" . }}.flow-lossless-install.tenxcloud.com
    namespaceSelector: {}
    objectSelector:
      matchLabels:
        flow-lossless: "true"
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: '*'
    sideEffects: None
    timeoutSeconds: 10
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "tmf.framework.fullname" . }}
        namespace: {{ include "tmf.framework.namespace" . }}
        path: /contract/install
        port: 443
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: {{ include "tmf.framework.fullname" . }}.contract.tenxcloud.com
    namespaceSelector: {}
    objectSelector:
      matchLabels:
        contract: "true"
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: '*'
    sideEffects: None
    timeoutSeconds: 10
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "tmf.framework.fullname" . }}
        namespace: {{ include "tmf.framework.namespace" . }}
        path: /outlier/ejection
        port: 443
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: {{ include "tmf.framework.fullname" . }}.outlier-ejection.tenxcloud.com
    namespaceSelector: {}
    objectSelector:
      matchLabels:
        outlier-ejection: "true"
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: '*'
    sideEffects: None
    timeoutSeconds: 10
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "tmf.framework.fullname" . }}
        namespace: {{ include "tmf.framework.namespace" . }}
        path: /push/empty/protection
        port: 443
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: {{ include "tmf.framework.fullname" . }}.push-empty-protection.tenxcloud.com
    namespaceSelector: {}
    objectSelector:
      matchLabels:
        push-empty-protection: "true"
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: '*'
    sideEffects: None
    timeoutSeconds: 10
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "tmf.framework.namespace" . }}/{{ include "tmf.env.fullname" . }}-ca
  name: {{ include "tmf.env.fullname" . }}
  labels:
    {{- include "tmf.framework.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "tmf.env.fullname" . }}
        namespace: {{ include "tmf.framework.namespace" . }}
        path: /mutate
        port: 443
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: {{ include "tmf.env.fullname" . }}.tenxcloud.com
    namespaceSelector:
      matchLabels:
        tmf-env-injector: "true"
    reinvocationPolicy: IfNeeded
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: '*'
    sideEffects: None
    timeoutSeconds: 10
---
