apiVersion: v1
kind: Secret
metadata:
  name: pkcs12-password-secret
  namespace: {{ include "tmf.framework.namespace" . }}
  labels:
    {{- include "tmf.framework.labels" . | nindent 4 }}
data:
  password: dGVueGNsb3Vk
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: contract-secret
  namespace: {{ include "tmf.framework.namespace" . }}
data:
  elasticsearchHost: {{ .Values.contract.elasticsearchHost | b64enc }}
  {{- if .Values.contract.elasticsearchUser }}
  elasticsearchUser: {{ .Values.contract.elasticsearchUser | b64enc }}
  {{- end }}
  {{- if .Values.contract.elasticsearchPassword }}
  elasticsearchPassword: {{ .Values.contract.elasticsearchPassword | b64enc }}
  {{- end }}
type: Opaque