---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "tmf.framework.labels" . | nindent 4 }}
    system/svcName: {{ include "tmf.framework.fullname" . }}
  name: {{ include "tmf.framework.fullname" . }}
  namespace: {{ include "tmf.framework.namespace" . }}
spec:
  ports:
    - name: tcp-framework-operator-0
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    k8s-app: {{ include "tmf.framework.fullname" . }}
  type: {{ .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "tmf.env.fullname" . }}
    helm.sh/chart: {{ include "tmf.framework.chart" . }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "tmf.env.fullname" . }}
  namespace: {{ include "tmf.framework.namespace" . }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: {{ include "tmf.env.fullname" . }}
  type: ClusterIP