---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tmf.framework.fullname" . }}
  namespace: {{ include "tmf.framework.namespace" . }}
  labels:
    {{- include "tmf.framework.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tmf.env.fullname" . }}
  namespace: {{ include "tmf.framework.namespace" . }}
  labels:
    {{- include "tmf.framework.labels" . | nindent 4 }}