apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "api.fullname" . }}-manager-{{ include "global.clusterReaderName" . }}
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services/proxy
    verbs:
      - create
      - get
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - create
      - get
      - list
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - patch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - get
      - list
      - patch
  - apiGroups:
      - extensions
    resources:
      - deployments
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - delete
      - patch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - update
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
  - apiGroups:
      - tmf.tenxcloud.com
    resources:
      - frameworks
      - approvals
      - gatewayroutes
      - loadbalancerules
      - ratelimitpolicies
    verbs:
      - create
      - get
      - list
      - update
      - delete
  - apiGroups:
      - tmf.tenxcloud.com
    resources:
      - frameworks/status
    verbs:
      - create
      - update
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
      - chaos-mesh.org
    resources:
      - httpchaos
    verbs:
      - create
      - get
      - delete
      - list