{{- if .Values.global.host -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spring-cloud-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spring-cloud-api
subjects:
  - kind: ServiceAccount
    name: spring-cloud-api
    namespace: {{ .Release.Namespace }}
{{- end -}}