{{- if .Values.oidcServer.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubebb.oidc-server
  labels:
    system/component: u4a
    system/u4a: oidc-server
rules:
- apiGroups: ["dex.coreos.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["create"]
- apiGroups:
  - policy
  resourceNames:
  - system
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - extensions
  resourceNames:
  - system
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - iam.tenxcloud.com
  resources:
  - groups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.tenxcloud.com
  resources:
  - groups/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubebb.oidc-server
  labels:
    system/component: u4a
    system/u4a: oidc-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubebb.oidc-server
subjects:
- kind: ServiceAccount
  name: oidc-server
  namespace: {{ .Release.Namespace }}
{{- end }}
