deployment:
  rating_enable: false
  image: kubebb/core:v0.1.5
  imagePullPolcy: IfNotPresent
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
webhook:
  enable: false

storage:
  enable: false
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  storageSize: 5Gi

defaultRepository:
  enable: false
